server:
  port: 0

spring:
  application:
    name: external-inquiries-service

eureka:
  instance:
    appname: ${spring.application.name}
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:2022/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
